---
stages:
  - code-tests
  - build
  - integration-tests

variables:
  CGO_ENABLED: 0

go-tests:
  stage: code-tests
  tags:
    - containerlab
  script:
    # create empty files to make clab happy
    - sudo mkdir -p /etc/containerlab/templates/srl && sudo touch /etc/containerlab/templates/srl/srlconfig.tpl
    - CGO_ENABLED=1 go test -cover -race ./...

build-containerlab:
  stage: build
  tags:
    - containerlab
  script:
    - sudo go build -o /usr/bin/containerlab

smoke-tests:
  stage: integration-tests
  tags:
    - containerlab
  script:
    - source ~/venvs/rf/bin/activate
    - bash ./tests/rf-run.sh ./tests/01-smoke
