---
stages:
  - code-tests
  - build
  - integration-tests

variables:
  CGO_ENABLED: 0

go-tests:
  stage: code-tests
  tags:
    - containerlab
  script:
    - CGO_ENABLED=1 go test -cover -race ./...

build-containerlab:
  stage: build
  tags:
    - containerlab
  script:
    - go build
