---
stages:
  - code-tests
  - build
  - integration-tests

go-tests:
  stage: code-tests
  tags:
    - containerlab
  script:
    - go test -cover -race ./...

build-containerlab:
  stage: build
  tags:
    - containerlab
  script:
    - go build
