project_name: containerlab
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/srl-wim/container-lab/cmd.version={{.Version}} -X github.com/srl-wim/container-lab/cmd.commit={{.ShortCommit}} -X github.com/srl-wim/container-lab/cmd.date={{.Date}}
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: containerlab
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: containerlab
    maintainer: Wim Henderickx <wim.henderickx@nokia.com>, Karim Radhouani <medkarimrdi@gmail.com>, Roman Dodin <dodin.roman@gmail.com>
    homepage: https://containerlab.srlinux.dev
    description: |
      containerlab deploys containerized networking topologies
    vendor: Nokia
    license: GNU GPLv3
    formats:
      - rpm
      - deb
    bindir: /usr/bin
    contents:
      - src: ./lab-examples/**/*
        dst: /etc/containerlab/lab-examples
      - src: ./templates/**/*
        dst: /etc/containerlab/templates
      - src: /usr/bin/containerlab
        dst: /usr/bin/clab
        type: symlink
