# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

project_name: containerlab
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/srl-labs/containerlab/cmd.version={{.Version}} -X github.com/srl-labs/containerlab/cmd.commit={{.ShortCommit}} -X github.com/srl-labs/containerlab/cmd.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post: upx "{{ .Path }}"
archives:
  - replacements:
      linux: Linux
    files:
      - lab-examples/**/*
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
publishers:
  - name: fury.io deb/rpm packages
    ids:
      - containerlab # this id belongs to nfpm section and is used to only upload artifacts from nfpm
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/netdevops/
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: containerlab
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: containerlab
    maintainer: Wim Henderickx <wim.henderickx@nokia.com>, Karim Radhouani <medkarimrdi@gmail.com>, Roman Dodin <dodin.roman@gmail.com>
    homepage: https://containerlab.srlinux.dev
    description: |
      containerlab deploys containerized networking topologies
    vendor: Nokia
    license: GNU GPLv3
    formats:
      - rpm
      - deb
    bindir: /usr/bin
    contents:
      - src: ./lab-examples
        dst: /etc/containerlab/lab-examples
      # - src: ./tools
      #   dst: /etc/containerlab/tools
      - src: ./templates
        dst: /etc/containerlab/templates
      - src: /usr/bin/containerlab
        dst: /usr/bin/clab
        type: symlink
