name: build-devcontainer
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      CLAB_VERSION:
        description: "Containerlab version"
        required: false

      TAG:
        description: "Additional container image tag"
        required: false
  # trigger on published release event
  # to created the devspace container when the packages are published
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  devcontainer:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/clab-devcontainer
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
            # git short commit
            type=sha
            # manually set tag
            type=raw,value=${{ inputs.tag }}

      - name: Build dev container image
        uses: docker/build-push-action@v6
        env:
          CLAB_VERSION: ${{ inputs.clab_version }}
        with:
          file: .devcontainer/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: linux/amd64,linux/arm64
