name: codespaces-devcontainer
on:
  workflow_dispatch:
    inputs:
      CLAB_VERSION:
        description: "Containerlab version"
        required: false

env:
  REGISTRY: ghcr.io

jobs:
  codespaces-devcontainer:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            # git short commit
            type=sha

      - name: Extract tags
        id: extract-tags
        run: |
          TAGS=$(echo '${{ steps.meta.outputs.tags }}' | awk -F: '{print $2}' | paste -sd "," -)
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Pre-build dev container image 🔨
        uses: devcontainers/ci@v0.3
        env:
          CLAB_VERSION: ${{ inputs.clab_version }}
        with:
          subFolder: .github/containers/dind
          imageName: ghcr.io/${{ github.repository }}/clab-codespaces
          imageTag: ${{ steps.extract-tags.outputs.tags }}
          push: always
