name: smoke-tests

"on":
  workflow_call:
    inputs:
      py_ver:
        required: true
        type: string

jobs:
  smoke-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      matrix:
        runtime:
          - "docker"
          - "podman"
    # allow podman job to fail, since it started to fail on github actions
    continue-on-error: ${{ matrix.runtime == 'podman' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: containerlab

      - name: Move containerlab to usr/bin
        run: sudo mv ./containerlab /usr/bin/containerlab && sudo chmod a+x /usr/bin/containerlab

      - name: Setup Podman
        if: matrix.runtime == 'podman'
        run: sudo bash ./.github/workflows/install-podman.sh

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.py_ver }}
          cache: pip
          cache-dependency-path: "tests/requirements.txt"

      - name: Install robotframework
        run: |
          pip install -r tests/requirements.txt

      - name: Run smoke tests
        run: |
          bash ./tests/rf-run.sh ${{ matrix.runtime }} ./tests/01-smoke

      # upload test reports as a zip file
      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: 01-smoke-log-${{ matrix.runtime }}
          path: ./tests/out/*.html

      # upload coverage report from unit tests, as they are then
      # merged with e2e tests coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-smoke-tests-${{ matrix.runtime }}
          path: /tmp/clab-tests/coverage/*
          retention-days: 7
